extends Resource
class_name CombatTypes

enum StunKind { NONE, BLOCKED, PARRIED }

enum CombatState {
	IDLE, STARTUP, ATTACKING, PARRY_ACTIVE, PARRY_SUCCESS, RECOVERING, STUNNED, GUARD_BROKEN,
	DODGE_STARTUP, DODGE_ACTIVE, DODGE_RECOVERING
}
